* Some stuff for my work.

** Blacklist
*** Configuration parameters
   All params in app.config
   You need to change only:
**** xml - relative path to XML request file
**** sign - relative path to sign file
**** trace - relative path to trace log file
**** doc_root - absolute path to application root dir
**** port - port web server listen on
**** listen_on - IPv4 address web server listen on
**** hostname - web server virtual host hostname
*** Start as standalone process.
   Load data from Russian government registry for site blocking.
   Need to have XML request and sign files.
   Server start as:
   #+BEGIN_EXAMPLE Erlang
    registry:start(XMLRequestFile, SignFile).
   #+END_EXAMPLE
   For example:
   #+BEGIN_EXAMPLE Erlang
    registry:start("priv/request.xml", "priv/request.bin").
   #+END_EXAMPLE
   Server status:
   #+BEGIN_EXAMPLE Erlang
    registry:status().
   #+END_EXAMPLE
   Example output:
   #+BEGIN_EXAMPLE Erlang
    registry:status().

    [{"XMLRequest","priv/request.xml"},
     {"XMLRequestSign","priv/request.bin"},
     {"lastDumpDate","16-May-2014, 06:04"},
     {"NextAction","send_req"},
     {"UpdateCounter",2},
     {"LastError",[]},
     {"CodeString",[]},
     {"LastTryCount",1}]
   #+END_EXAMPLE
   Server store downloaded archive to priv/arch and last XML dump to priv/dump.xml
*** Start as erlang application
   #+BEGIN_EXAMPLE Erlang
   application:start(rkn_registry).
   #+END_EXAMPLE
   And then browse http://localhost:<port_number>/data.yaws?act=<ACTION>, where
   ACTION = [list | status | filter = [ip | domain | org | date | decision]]
